### ISSUE TITLE
"npm run render" leads to "Error: Error: ffmpeg exited with code 1:"

### ISSUE THREAD

**Issue by ullenboom** [redotvideo/revideo#182]
Next one :)

```
>npm run render

> my-revideo-project@0.0.0 render
> tsc && node dist/render.js

Rendering video...
Render progress, worker 0: 7%
Render progress, worker 0: 48%
Render progress, worker 0: 100%
Render progress, worker 0: 100%
Render progress, worker 0: 100%
Render progress, worker 0: 100%
Error: Error: ffmpeg exited with code 1:
    at ChildProcess.<anonymous> (C:\Users\christian\Dropbox\Eigene_Dokumente\maven\revideo\node_modules\fluent-ffmpeg\lib\processor.js:180:22)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: ffmpeg exited with code 1:
    at ChildProcess.<anonymous> (C:\Users\christian\Dropbox\Eigene_Dokumente\maven\revideo\node_modules\fluent-ffmpeg\lib\processor.js:180:22)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

Node.js v20.15.0
```

I get an incomplete video-0.mp4 with audio in my output folder.

![image](https://github.com/redotvideo/revideo/assets/5071169/82c7b397-6c5a-463f-ab84-e72bde756e8e)

**Comment by justusmattern27** [comment]
@ullenboom the error log is not very informative unfortunately. I would guess that this is something about your input file (video or audio file) or your ffmpeg installation (more likely). I think you are also one of our first users running revideo on windows, so I would think it has to do with system dependencies around ffmpeg :D

By default, revideo comes with an ffmpeg binary. Maybe you could try using your own installation. First, check that you have ffmpeg & ffprobe installed (run `ffmpeg -v` and `ffprobe -v`). If so, set the following environment variables:

```
FFMPEG_PATH=ffmpeg
FFPROBE_PATH=ffprobe
```

If you don't have ffmpeg and ffprobe installed, try doing that first and then set the environment variables

**Comment by ullenboom** [comment]
Both tools are installed and in the PATH. Current versions. I found another problem, that ffmpeg-static\ffmpeg.exe was not installed. This seems to be a bug: https://github.com/eugeneware/ffmpeg-static/issues/131. But solvable:

```
npm install --save @ffmpeg-installer/ffmpeg
npm install --save @ffprobe-installer/ffprobe
```

Now the EXE is at the right place. But the error is the same.

Setting `*_PATH` doesn't make any difference. Therefore, the issue lies with `fluent-ffmpeg`, not `revideo`.

**Comment by plylrnsdy** [comment]
I have a similar issue with the project created by `npm init @revideo@latest`:

```
Executing task in folder revideo: npm run render 


> revideo@0.0.0 render
> tsc && node dist/render.js

Rendering video...
Worker 0: JSHandle:Calling fullSource for logo.png
Worker 0: JSHandle:Setting assetRoot
Worker 0: JSHandle:/
Worker 0: JSHandle:Calling fullSource for logo.png
Worker 0: JSHandle:Calling fullSource for logo.png
Worker 0: JSHandle:Setting assetRoot
Worker 0: JSHandle:/
Worker 0: JSHandle:Calling fullSource for logo.png
Worker 0: JSHandle:Setting assetRoot
Worker 0: JSHandle:/
Worker 0: JSHandle:Calling fullSource for logo.png
Worker 0: JSHandle:Setting assetRoot
Worker 0: JSHandle:/
Worker 0: JSHandle:Calling fullSource for logo.png
Worker 0: JSHandle:Setting assetRoot
Worker 0: JSHandle:/
Worker 0: JSHandle:Calling fullSource for logo.png
Worker 0: JSHandle:Setting assetRoot
Worker 0: JSHandle:/
Worker 0: JSHandle:Calling fullSource for logo.png
Worker 0: JSHandle:Setting assetRoot
Worker 0: JSHandle:/
Worker 0: JSHandle:Calling fullSource for logo.png
Worker 0: JSHandle:Setting assetRoot
Worker 0: JSHandle:/
Worker 0: JSHandle:Calling fullSource for logo.png
Worker 0: JSHandle:Setting assetRoot
Worker 0: JSHandle:/
Render progress, worker 0: 2% 
Render progress, worker 0: 18% 
Render progress, worker 0: 35% 
Render progress, worker 0: 51% 
Render progress, worker 0: 64% 
Render progress, worker 0: 78% 
Render progress, worker 0: 99% 
Error creating silent audio file: Error: ffmpeg exited with code 1: Invalid duration specification for t: N/A

    at ChildProcess.<anonymous> (xxx\my-revideo-project\revideo\node_modules\.pnpm\fluent-ffmpeg@2.1.3\node_modules\fluent-ffmpeg\lib\processor.js:180:22)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ffmpeg exited with code 1: Invalid duration specification for t: N/A

    at ChildProcess.<anonymous> (xxx\my-revideo-project\revideo\node_modules\.pnpm\fluent-ffmpeg@2.1.3\node_modules\fluent-ffmpeg\lib\processor.js:180:22)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

Node.js v20.11.0
```

**Comment by langyamu** [comment]
I encountered the same error, tried 'motion canvas', and 'motion canvas' is working fine.

OS: Windows 11

```shell
Rendering video...
Render progress, worker 0: 7% 
Render progress, worker 0: 24% 
Render progress, worker 0: 81% 
Render progress, worker 0: 100% 
Render progress, worker 0: 100% 
Render progress, worker 0: 100% 
Render progress, worker 0: 100% 
Render progress, worker 0: 100% 
Render progress, worker 0: 100% 
Render progress, worker 0: 100% 
Render progress, worker 0: 100% 
Render progress, worker 0: 100% 
Render progress, worker 0: 100% 
Render progress, worker 0: 100% 
Error: Error: ffmpeg exited with code 1: Output #0, mp4, to 'output\video-visuals.mp4':
Output file #0 does not contain any stream

    at ChildProcess.<anonymous> (xxxxxx\learn-revideo-project\node_modules\.pnpm\fluent-ffmpeg@2.1.3\node_modules\fluent-ffmpeg\lib\processor.js:180:22)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ffmpeg exited with code 1: Output #0, mp4, to 'output\video-visuals.mp4':
Output file #0 does not contain any stream

    at ChildProcess.<anonymous> (xxxxxx\learn-revideo-project\node_modules\.pnpm\fluent-ffmpeg@2.1.3\node_modules\fluent-ffmpeg\lib\processor.js:180:22)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by MiniSuperDev** [comment]
Hi, I have the same error.
I only try tu run the `youtube-shorts` example.

I can see it work it in the preview mode with `npm run start`

But when I sue `npm run render` or trigger the render in the UI

I get this error

```sh
PS C:\revideo\examples\youtube-shorts> npm run render

> revideo@0.0.0 render
> tsc && node dist/render.js

Worker 0: JSHandle:finished downloading
Render progress, worker 0: 1% 
Render progress, worker 0: ...%
Render progress, worker 0: 100% 
Error: Error: ffmpeg exited with code 1: Output #0, mp4, to 'output\video-visuals.mp4':
Output file #0 does not contain any stream

    at ChildProcess.<anonymous> (C:\revideo\examples\youtube-shorts\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ffmpeg exited with code 1: Output #0, mp4, to 'output\video-visuals.mp4':
Output file #0 does not contain any stream

    at ChildProcess.<anonymous> (C:\revideo\examples\youtube-shorts\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

Node.js v20.13.1
```

Then I use my own installation of ffmpep and also don't work
```
PS C:\revideo\examples\youtube-shorts> npm run render

> revideo@0.0.0 render
> tsc && node dist/render.js
Worker 0: JSHandle:finished downloading
Error processing audio for asset key: example/Audio2[1] Error: spawn C:/ffmpeg/bin ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:/ffmpeg/bin',
  path: 'C:/ffmpeg/bin',
  spawnargs: [ '-formats' ]
}
error in request handler Error: spawn C:/ffmpeg/bin ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:/tools/ffmpeg-master-latest-win64-gpl/bin',
  path: 'C:/tools/ffmpeg-master-latest-win64-gpl/bin',
  spawnargs: [ '-formats' ]
}
Render progress, worker 0: 3% 
Render progress, worker ...%
Render progress, worker 0: 100% 
Error creating silent audio file: Error: sp/ffmpeg/bin ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:/ffmpeg/bin',
  path: 'C:/ffmpeg/bin',
  spawnargs: [ '-formats' ]
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: spawn C:/ffmpeg/bin ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:/ffmpeg/bin',
  path: 'C:/ffmpeg/bin',
  spawnargs: [ '-formats' ]
}

Node.js v20.13.1

```

Thanks

**Comment by AmitDJagtap** [comment]
Yeep still getting error on Windows.

**Comment by Auties00** [comment]
Same error, any fixes?

**Comment by AidanWelch** [comment]
Still getting the same issue on Windows.  From what I can gather the issue isn't with ffmpeg but is instead with the rendered visuals- because the `visuals.mp4` in my temp folder before concatenation is unreadable.

**Comment by AidanWelch** [comment]
Okay I figured it out, `mp4-wasm` which is used by `WasmExporter` is broken on Windows https://github.com/mattdesl/mp4-wasm/issues/6

**Comment by AidanWelch** [comment]
You the mean time you can get around it by using the ffmpeg exporter though it seems relatively slow for me:

```ts
export default makeProject({
  scenes: [scene],
  settings: {
    shared: {
      size: {x: 1920, y: 2400},
    },
    rendering: {
      exporter: {
        name: '@revideo/core/ffmpeg',
        options: {
          format: 'mp4'
        }
      }
    }
  },
});
```

**Comment by marioguima** [comment]
Same error, anything to fix?

**Comment by marioguima** [comment]
Dockerfile:
`FROM node:20-slim AS base
WORKDIR /app

# Instala bibliotecas do sistema necessárias para Chromium/Puppeteer
RUN apt-get update && apt-get install -y --no-install-recommends \
    gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
    libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 \
    libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
    libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 \
    libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 \
    libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
    libxtst6 libnss3 lsb-release xdg-utils wget \
    libgbm1 \
    fonts-liberation fonts-ipafont-gothic x11-utils \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm ci

FROM base AS dev
COPY . .
ENV NODE_ENV=development
EXPOSE 9000
CMD ["npm", "run", "start"]
`

docker-compose.yml:
`version: "3.8"
services:
  revideo-dev:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "9876:9000"      # host:container 
    command: ["npm", "run", "start"]
`

render.ts:
`import { renderVideo } from '@revideo/renderer';

async function render() {
  console.log('Rendering video...');

  const file = await renderVideo({
    projectFile: './src/project.tsx',
    settings: {
      logProgress: true,
      // ← Add this block to pass the sandbox flags
      puppeteer: {
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox'
        ]
      }
    }
  });

  console.log(`Rendered video to ${file}`);
}

render();
`

**Comment by marioguima** [comment]
I'm using Docker Desktop
in the exec tab, I ran > npm run render

Ps. 01-minimal-project is the name of my project

It generated the video, but without audio

This is the log:

```bash
# npm run render

> 01-minimal-project@0.0.0 render
> tsc && node dist/render.js

Rendering video...
Port 9000 is in use, trying another one...
Worker 0: JSHandle:finished downloading
error checking for audioStream for file https://revideo-example-assets.s3.amazonaws.com/stars.mp4 Error: ffprobe was killed with signal SIGSEGV
ffprobe version N-66595-gc2b38619c0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      58. 14.100 / 58. 14.100
  libavcodec     60. 22.100 / 60. 22.100
  libavformat    60. 10.100 / 60. 10.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9.  8.102 /  9.  8.102
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100

    at ChildProcess.<anonymous> (/app/node_modules/fluent-ffmpeg/lib/ffprobe.js:235:22)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
error in request handler Error: ffprobe was killed with signal SIGSEGV
ffprobe version N-66595-gc2b38619c0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      58. 14.100 / 58. 14.100
  libavcodec     60. 22.100 / 60. 22.100
  libavformat    60. 10.100 / 60. 10.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9.  8.102 /  9.  8.102
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100

    at ChildProcess.<anonymous> (/app/node_modules/fluent-ffmpeg/lib/ffprobe.js:235:22)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
Render progress, worker 0: 17% 
Render progress, worker 0: 25% 
Render progress, worker 0: 44% 
Render progress, worker 0: 60% 
Render progress, worker 0: 79% 
Render progress, worker 0: 96% 
Rendered video to output/video.mp4
# 
```

**Comment by marioguima** [comment]
I couldn't test it, but there is something that might help.

In this implementation mp4-wasm Working on windows  https://codepen.io/marco_fugaro/pen/yLKmjeM?editors=1010

![Image](https://github.com/user-attachments/assets/c3da9c47-0950-46e6-affd-9faed777f211)

beacause this:

![Image](https://github.com/user-attachments/assets/51fac1c2-1c69-448d-a155-791c31249aa8)

```bash
 // this makes it work on windows
 format: 'avc',
```

In this file, in the revideo source code
packages\core\src\exporter\WasmExporter.ts

there is this block:
```bash
 this.encoder = mp4.createWebCodecsEncoder({
    width: this.settings.size.x,
    height: this.settings.size.y,
    fps: this.project.settings.rendering.fps,
  });
```

new code:
```bash
 this.encoder = mp4.createWebCodecsEncoder({
    width: this.settings.size.x,
    height: this.settings.size.y,
    fps: this.project.settings.rendering.fps,
    // this makes it work on windows
    format: 'avc',
  });
```

But I can't test it
If anyone can test it, it would be great to see the results.
