### ISSUE TITLE
Multiple workers cause Input stream error

### ISSUE THREAD

**Issue by Pita** [redotvideo/revideo#230]
Getting these errors when using multiple workers. I can provide a tar to reproduce it if you want. I'm on 0.5.3

```
Worker 0: JSHandle:error from browser process:
Worker 0: JSHandle:An error occurred while exporting the video: Input stream error: stream.push() after EOF
/Users/petermartischka/code/kato/etc/video/node_modules/@revideo/renderer/lib/server/render-video.js:125
            reject(new Error(message));
                   ^

Error: An error occurred while exporting the video: Input stream error: stream.push() after EOF
    at Binding.<anonymous> (/Users/petermartischka/code/kato/etc/video/node_modules/@revideo/renderer/lib/server/render-video.js:125:20)
    at Binding.run (/Users/petermartischka/code/kato/etc/video/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Binding.js:125:46)
    at #onBindingCalled (/Users/petermartischka/code/kato/etc/video/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:598:24)
    at /Users/petermartischka/code/kato/etc/video/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:164:39
    at /Users/petermartischka/code/kato/etc/video/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
    at Array.map (<anonymous>)
    at Object.emit (/Users/petermartischka/code/kato/etc/video/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:61:20)
    at FrameManager.emit (/Users/petermartischka/code/kato/etc/video/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:83:23)
    at #onMainWorldBindingCalled (/Users/petermartischka/code/kato/etc/video/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:119:32)
    at /Users/petermartischka/code/kato/etc/video/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7

Node.js v20.11.1
```

**Comment by Pita** [comment]
I got this issue by starting multiple render processes, as well as when defining multiple workers. But I don't get it when defining a seperate vite port for reach render worker.

**Comment by justusmattern27** [comment]
@Pita how do you define the ports for multiple workers? 

If you're uisng the `worker` argument in `renderVideo`, ports should automatically be chosen so that there's no conflict. Do you use the port argument of viteConfig? If so, I would recommend you to use the viteBasePort argument, as it prevents conflicts between ports: https://docs.re.video/api/renderer/renderVideo/

**Comment by Pita** [comment]
Yes I used the `vitePort` setting. This is how i made it work

```ts
const render = async (video: Scene, index: number) => {
  console.log(`Rendering video ${video} (${SCENES[video]})...`);

  // This is the main function that renders the video
  const file = await renderVideo({
    projectFile: "./src/project.ts",
    variables: { name: video },
    settings: {
      logProgress: true,
      workers: 1,
      dimensions: SCENES[video] === "portrait" ? [1080, 1920] : [1920, 1080],
      outFile: `${video}.mp4`,
      viteBasePort: 9000 + index, // <--- this fixed it
    },
  };

  console.log(`Rendered video to ${file}`);
}, 4);


async function renderAll() {
  await Promise.all(videos.map((video, i) => render(video, i)));
}

renderAll();
```

**Comment by Pita** [comment]
I can't really reproduce this anymore for some reason 🤔. Closing for now
