### ISSUE TITLE
Not sure if it will have the effect I want

### ISSUE THREAD

**Issue by QC2168** [redotvideo/revideo#244]
I want to enter the following code

```typescript
import {Audio, Img, Video, makeScene2D} from '@revideo/2d';
import {all, chain, createRef, waitFor} from '@revideo/core';

export default makeScene2D(function* (view) {
  const logoRef = createRef<Img>();

  yield view.add(
    <>
      <Video
        src={'https://revideo-example-assets.s3.amazonaws.com/stars.mp4'}
        size={['100%', '100%']}
        play={true}
      />
      <Audio
        src={'https://revideo-example-assets.s3.amazonaws.com/chill-beat.mp3'}
        play={true}
        time={17.0}
      />
    </>,
  );

  yield* waitFor(1);

  view.add(
    <Img
      width={'1%'}
      ref={logoRef}
      src={
        'https://revideo-example-assets.s3.amazonaws.com/revideo-logo-white.png'
      }
    />,
  );

  yield* chain(
    all(logoRef().scale(40, 2), logoRef().rotation(360, 2)),
    logoRef().scale(60, 1),
  );
});
```

revideo only return video data，maybe blob type data

I running `npm init @revideo@latest` and `vite serve`, it open editor
I don't want these features. They're too bulky

**Comment by justusmattern27** [comment]
Hey, if you just want to render the video and not use the editor, you can execute the src/render.ts file (npm run render)

**Comment by QC2168** [comment]
OK I try it，thanks！

**Comment by justusmattern27** [comment]
perfect - I am closing this for now, feel free to reopen if any issues arise

**Comment by QC2168** [comment]
an error occurred @justusmattern27 

```
PS E:\project\my-revideo-project> node dist/render.js
Rendering video...
E:\project\my-revideo-project\node_modules\.pnpm\puppeteer-core@22.15.0\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\LifecycleWatcher.js:103
            this.#terminationDeferred.resolve(new Error('Navigating frame was detached'));
                                              ^

Error: Navigating frame was detached
    at #onFrameDetached (E:\project\my-revideo-project\node_modules\.pnpm\puppeteer-core@22.15.0\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\LifecycleWatcher.js:103:47)
    at E:\project\my-revideo-project\node_modules\.pnpm\puppeteer-core@22.15.0\node_modules\puppeteer-core\lib\cjs\third_party\mitt\mitt.js:62:7
    at Array.map (<anonymous>)
    at Object.emit (E:\project\my-revideo-project\node_modules\.pnpm\puppeteer-core@22.15.0\node_modules\puppeteer-core\lib\cjs\third_party\mitt\mitt.js:61:20)
    at CdpFrame.emit (E:\project\my-revideo-project\node_modules\.pnpm\puppeteer-core@22.15.0\node_modules\puppeteer-core\lib\cjs\puppeteer\common\EventEmitter.js:83:23)
    at #removeFramesRecursively (E:\project\my-revideo-project\node_modules\.pnpm\puppeteer-core@22.15.0\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\FrameManager.js:450:15)
    at #onClientDisconnect (E:\project\my-revideo-project\node_modules\.pnpm\puppeteer-core@22.15.0\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\FrameManager.js:94:42)

Node.js v20.16.0
PS E:\project\my-revideo-project> 
```
