### ISSUE TITLE
Issue Rendering Transperant Videos: Error No input specified

### ISSUE THREAD

**Issue by maheshmb13** [redotvideo/revideo#321]
Trying to render transparent videos example provided in the documentation.
[Revideo Transparent videos](https://docs.re.video/transparent-video)

yarn start
yarn run v1.22.21
$ revideo editor --projectFile ./src/project.tsx
Port 9000 is in use, trying another one...
Editor running on port 9001
10:42:01 AM [vite] ✨ new dependencies optimized: @revideo/2d/editor
10:42:01 AM [vite] ✨ optimized dependencies changed. reloading
/Users/maheshbabu/Workspace/my-animation/my-revideo-project/node_modules/fluent-ffmpeg/lib/ffprobe.js:128
        return handleCallback(new Error('No input specified'));
                              ^

Error: No input specified
    at proto.ffprobe (/Users/maheshbabu/Workspace/my-animation/my-revideo-project/node_modules/fluent-ffmpeg/lib/ffprobe.js:128:31)
    at FfmpegCommand.ffprobe (/Users/maheshbabu/Workspace/my-animation/my-revideo-project/node_modules/fluent-ffmpeg/lib/fluent-ffmpeg.js:221:20)
    at /Users/maheshbabu/Workspace/my-animation/my-revideo-project/node_modules/@revideo/ffmpeg/dist/utils.js:210:16
    at new Promise (<anonymous>)
    at getVideoMetadata (/Users/maheshbabu/Workspace/my-animation/my-revideo-project/node_modules/@revideo/ffmpeg/dist/utils.js:209:12)
    at new VideoFrameExtractor (/Users/maheshbabu/Workspace/my-animation/my-revideo-project/node_modules/@revideo/ffmpeg/dist/video-frame-extractor.js:39:38)
    at FFmpegBridge.handleDecodeVideoFrame (/Users/maheshbabu/Workspace/my-animation/my-revideo-project/node_modules/@revideo/vite-plugin/lib/partials/ffmpegBridge.js:172:25)
    at /Users/maheshbabu/Workspace/my-animation/my-revideo-project/node_modules/@revideo/vite-plugin/lib/partials/ffmpegBridge.js:54:69
    at handlePostRequest (/Users/maheshbabu/Workspace/my-animation/my-revideo-project/node_modules/@revideo/vite-plugin/lib/partials/ffmpegBridge.js:26:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.0
error Command failed with exit code 1.

**Comment by Farr1102** [comment]
Have you solved it? I've also encountered this problem
