### ISSUE TITLE
Bug : Unable to load any shader

### ISSUE THREAD

**Issue by rgdev** [redotvideo/revideo#336]
## Problem

I'm unable to load any glsl shader (experimentalFeatures=true) on any Node.

I get this stackstrace in the editor and browser console : 

**The scene is not available in the current context.**
The problem occurred here:
at useScene (/node_modules/.vite/deps/chunk-5ZUPHDUC.js:3548:11)
at useScene2D (/node_modules/.vite/deps/chunk-WKOHVKNO.js:54378:10)
at Img2.shaderCanvas (/node_modules/.vite/deps/chunk-WKOHVKNO.js:55282:19)
at Img2.render (/node_modules/.vite/deps/chunk-WKOHVKNO.js:55343:29)
at async View2D2.drawChildren (/node_modules/.vite/deps/chunk-WKOHVKNO.js:55370:7)
at async View2D2.draw (/node_modules/.vite/deps/chunk-WKOHVKNO.js:56378:5)
at async View2D2.render (/node_modules/.vite/deps/chunk-WKOHVKNO.js:55351:7)
at async View2D2.render (/node_modules/.vite/deps/chunk-WKOHVKNO.js:57430:5)
at async Scene2D.draw (/node_modules/.vite/deps/chunk-WKOHVKNO.js:106311:5)
at async Scene2D.render (/node_modules/.vite/deps/chunk-5ZUPHDUC.js:9278:7)
at async Stage.render (/node_modules/.vite/deps/chunk-5ZUPHDUC.js:8446:5)
at async (/node_modules/.vite/deps/chunk-AM5JXEGA.js:51601:5)
at async AsyncEventDispatcher.dispatch (/node_modules/.vite/deps/chunk-5ZUPHDUC.js:3140:5)
at async Player.run (/node_modules/.vite/deps/chunk-5ZUPHDUC.js:8365:5)
at async (/node_modules/.vite/deps/chunk-5ZUPHDUC.js:8378:11)

## How to reproduce

1. `npm init @revideo@latest`
2. select all defaults
3. `cd my-revideo-project`
4. `npm install`
5. add `myShader.glsl` next to `project.tsx` (I copied the example one [from the doc](https://docs.re.video/shaders/))
6. add import and reference shader on some node : 
```
  // ...
  import myShader from "./myShader.glsl"

  const scene = makeScene2D('scene', function* (view) {
   // ...
    view.add(
      <Img
        shaders={myShader}
        width={'1%'}
        ref={logoRef}
        src={
          'https://revideo-example-assets.s3.amazonaws.com/revideo-logo-white.png'
        }
      />,
    );
  // ...
  });
```
8. npm start

Try moving the seek head, as soon as the Node becomes active the editor errors out like so : 
<img width="688" alt="image" src="https://github.com/user-attachments/assets/c190f80b-5ecf-4bd1-bfa2-362b6389aa8d">

## Versions

Tested on Revideo 0.10.1 (all revideo packages on same version), Chrome 131.0.6778.86, MacOS 14 (arm64)

**Comment by rgdev** [comment]
Here's a more user-friendly stacktrace with .ts files : 

> main.tsx:43 Error: The scene is not available in the current context.
>     at useScene (useScene.ts:11:11)
>     at useScene2D (useScene2D.ts:5:19)
>     at Video.shaderCanvas (Node.ts:1549:19)
>     at Video.render (Node.ts:1649:29)
>     at async View2D.drawChildren (Node.ts:1684:7)
>     at async View2D.draw (Shape.ts:93:5)
>     at async View2D.render (Node.ts:1662:7)
>     at async View2D.render (View2D.ts:75:5)
>     at async Scene2D.draw (Scene2D.ts:59:5)
>     at async Scene2D.render (GeneratorScene.ts:163:7)
>     at async Stage.render (Stage.ts:87:5)
>     at async PreviewStage.tsx:21:7
>     at async Promise.all (:9000/index 0)
>     at async AsyncEventDispatcher.dispatch (AsyncEventDispatcher.ts:39:5)
>     at async Player.run (Player.ts:437:5)
>     at async Player.ts:454:11

From my understanding `Node.ts`'s `shaderCanvas()` is calling `useScene2D()` when `shaders.length > 0` except that `SceneStack.length === 0` (`useScene.ts`) when this happens.
I suppose either `shaderCanvas()` is called too late, or the scene isn't supposed to be popped so soon but i'm not familiar enough with the inner workings of Revideo / Motion Canvas to fully grasp the big picture here.
Any help from a project maintainer would be become :)

**Comment by rgdev** [comment]
Additionally I just tried to create a blank motion canvas project using latest version (3.17.0) and had no issue applying shaders on a node so I believe the issue is limited to revideo

**Comment by rgdev** [comment]
After some digging I think the issue is in `core/src/scenes/GeneratorScene.ts`, especially the `render()` function : 

```
  public async render(context: CanvasRenderingContext2D): Promise<void> {
    let iterations = 0;
    do {
      iterations++;
      await DependencyContext.consumePromises();
      context.save();
      context.clearRect(0, 0, context.canvas.width, context.canvas.height);
      await this.draw(context); // <-- key part
      context.restore();
    } while (DependencyContext.hasPromises() && iterations < 10);

    if (iterations > 1) {
      this.logger.debug(`render iterations: ${iterations}`);
    }
  }
```

The issue is that `await this.draw(context);` is called directly without being wrapped inside `execute()` therefore `startScene()` isn't called before executing the shader drawing logic and the `SceneStack` is empty resulting in the `The scene is not available in the current context` error

I can think of two solutions for now : 
1. edit `render()` and simply add the lifecycle functions around the draw call to ensure the scene stack is valid : 
```
  public async render(context: CanvasRenderingContext2D): Promise<void> {
  ...
      startScene(this);
      startPlayback(this.playback);
      await this.draw(context);
      endPlayback(this.playback);
      endScene(this);
  ...
  }
```

2. make `execute()` async and edit `render()` like so : 
```
  public async render(context: CanvasRenderingContext2D): Promise<void> {
  ...
      await this.execute(() => this.draw(context));
  ...
  }
```

with either fixes I get working shaders (at least in my basic test scene) but i'm not sure what's the best course of action as it involve changes in the core package
